services:
  - type: web
    name: luzbrill-frontend
    env: node
    region: oregon
    buildCommand: yarn install && yarn build
    startCommand: npx serve -s build -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: REACT_APP_API_URL
        value: https://luzbrill-backend.onrender.com/api
